# Scan the Dockerfile for issues & CVEs
name: Docker Lint

on: 
    workflow_call:
permissions:
  contents: read
  
jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            
            - name: Validate Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile