name: Main Pipeline

on:
  push:
    branches: [main]


jobs:
  code-quality:
        uses: ./.github/workflows/code-quality.yml
  secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit
  dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
  docker-scan:
        uses: ./.github/workflows/docker-lint.yml

  tests:
        uses: ./.github/workflows/tests.yml
  build:
    needs: [code-quality, secrets-scan, dependency-scan, docker-scan, tests]
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: "3.12"
    secrets: inherit

  docker:
    needs: build
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: github-actions-capstone
      tag: latest
    secrets: inherit
  
  # Image scan 
  trivy:
    needs: [docker]
    uses: ./.github/workflows/image-scan.yml
    permissions:
      contents: read
      security-events: write
    secrets: inherit
    
  deploy:
    needs: trivy
    uses: ./.github/workflows/deploy-to-server.yml
    secrets: inherit