name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit
  dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

  build:
    needs: [secrets-scan, dependency-scan]
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: "3.12"
    secrets: inherit

  docker:
    needs: build
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: github-actions-capstone
      tag: latest
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}
  
  # Image scan 
  trivy:
    needs: [docker]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
    
  deploy:
    needs: trivy
    uses: ./.github/workflows/deploy-to-server.yml
    secrets: inherit